name: GitStats Examples

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The repo path to clone'
        required: false
        default: 'https://github.com/jenkinsci/jenkins.git'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gnuplot

    - name: Generate GitStats Report
      run: |
        pipx install gitstats
        git clone ${{ inputs.name }}
        repo_name=$(basename -s .git "${{ inputs.name }}")
        echo "REPO_NAME=$repo_name" >> $GITHUB_ENV
        gitstats ./$repo_name gitstats-report

    - name: Commit and Push Report to Current Branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Stage the generated gitstats-report
        git add gitstats-report
        git commit -m "Add GitStats report"
        
        # Push to the current branch
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
